package com.myspace.a2c_simulation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Sample implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("age")
	private java.lang.Integer age;

	@org.kie.api.definition.type.Label(value = "surname")
	private java.lang.String surname;

	public Sample() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getSurname() {
		return this.surname;
	}

	public void setSurname(java.lang.String surname) {
		this.surname = surname;
	}

	public Sample(java.lang.String name, java.lang.Integer age,
			java.lang.String surname) {
		this.name = name;
		this.age = age;
		this.surname = surname;
	}

}