package com.myspace.a2c_simulation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Sample implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Sample() {
    }




}